Repository ludgranados/react-bartender-ts, pull requests merged in 2021-05, with the labels that each got.

#10 feat(app-routes): setup web-app-routes
  src/routers/AppRoutes.tsx
Labels: feature, in progress

#12 feat(data-types): adding drink type
  src/types.d.ts
Labels: feature, in progress

#21 feat(single-drink-component): created single drink card component in single drink page
  src/components/SingleDrinkCard.tsx
  src/pages/SingleDrink.tsx
Labels: feature, in progress

#25 Feature: add Global state and Api
  src/api/apiConfig.ts
  src/context/GlobalContext.tsx
  src/types.d.ts
Labels: feature, in progress

#26 refact(data-types): included all data variable names
  src/types.d.ts
Labels: in progress, refactor

#28 fix(data-types): fixed spelling error
  src/types.d.ts
Labels: bug, in progress

#29 feat(cocktail-api): printed out data with use of context, axios, and apiConfig
  src/App.tsx
  src/context/GlobalContext.tsx
  src/pages/Home.tsx
  src/types.d.ts
Labels: feature, in progress

#33 refact(single-drink): changed styling and format of page and component
  src/components/SingleDrinkCard.tsx
  src/pages/SingleDrink.tsx
Labels: in progress, refactor

#35 refact(single-drink): able to get single properties to print out; updated styling
  src/App.css
  src/components/Loader.tsx
  src/components/SingleDrinkCard.tsx
  src/context/GlobalContext.tsx
  src/pages/Home.tsx
  src/pages/SingleDrink.tsx
  src/types.d.ts
Labels: bug, in progress

#38 feat(single-drink): removed partially empty lines containing null values
  src/components/SingleDrinkCard.tsx
Labels: feature, in progress

#43 refact(single-drink-card): rearranged order of info to follow logically
  src/components/SingleDrinkCard.tsx
Labels: in progress, refactor

#44 feat(home): added search filter to filter drinks by name
  src/pages/Home.tsx
Labels: feature, in progress
